### ISSUE TITLE
[TS-2] tasksh segfaults if quotes not closed

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskshell#2]
_Fidel Mato on 2013-05-23T17:27:34Z says:_ 

 [in Debian 6.0 , Taskwarrior 2.3.0 , Spanish localization]

tasksh fails and exits if quotes are not properly closed.

(It seems that... ) If the incomplete quoted command is not the first issued in the current session
it fails with segmentation fault:

<pre>$ tasksh
task 2.3.0 shell

Escriba un comando de task (como 'list'), o pulse 'Enter'.
No hace falta incluir el propio comando 'task'.
Escriba 'quit' (o 'bye', 'exit') para terminar la sesión.

task> add "tres"
Creada tarea 127.
task> add "tres
Violación de segmento
$</pre>

If the command is the first issued, error refers to an invalid pointer:

<pre>$ tasksh
task 2.3.0 shell

Escriba un comando de task (como 'list'), o pulse 'Enter'.
No hace falta incluir el propio comando 'task'.
Escriba 'quit' (o 'bye', 'exit') para terminar la sesión.

task> add "tres
*** glibc detected *** tasksh: free(): invalid pointer: 0x00007f5c7be570b8 ***
======= Backtrace: =========
/lib/libc.so.6(+0x71e16)[0x7f5c7bb6ae16]
/lib/libc.so.6(cfree+0x6c)[0x7f5c7bb6fb8c]
/lib/libc.so.6(wordfree+0x39)[0x7f5c7bbb8269]
tasksh(_ZN7WordexpD1Ev+0x18)[0x57b5e8]
tasksh(main+0xe68)[0x46495c]
/lib/libc.so.6(__libc_start_main+0xfd)[0x7f5c7bb17c8d]
tasksh[0x463a39]
======= Memory map: ========
...
$</pre>

File attached with complete backtrace.

**Comment by pbeckingham** [comment]
[TS-2_incomplete_quotes_back.txt](https://github.com/GothenburgBitFactory/taskshell/files/1755292/TS-2_incomplete_quotes_back.txt)
