### ISSUE TITLE
[TS-27] Adding an auto-refresh watch-like function

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskshell#26]
_bjonnh on 2016-06-24T20:55:59Z says:_ 

 Having a way to start an auto-refresh mode, that refresh a specific report (last one?) until the user press a key (either any key, or a specific one).

I see two possibilities:
1) Auto-refresh last one
Means that the last report must be saved
2) add a watch command, so you can do watch +foo +bar project:something

Solution 2 is my favorite.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2016-06-24T20:55:59Z
Modified: 2016-09-05T04:53:04Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2016-09-04T17:20:54Z says:_ 

 Closing this issue.  From the shell, this could be done with:

```
$ watch -n 5 task +foo +bar project:something list
```

Or from within tasksh 1.1.0 (not yet released) done with:

```
tasksh> ! watch -n 5 task +foo +bar project:something list
```

So replacing one shell command with one tasksh command isn't much of a win.

**Comment by taskwarrior** [comment]
_Daniel Shahaf on 2016-09-05T04:53:04Z says:_ 

 (The above recipe assumes [the Linux `watch` command|http://linux.die.net/man/1/watch].  On other OSes, such as FreeBSD, the OS's `watch` command does something [entirely different|https://www.freebsd.org/cgi/man.cgi?watch].)

**Comment by aaroneaton** [comment]
For anyone coming across this and wondering why colors aren't showing when using `watch`, you need to add some configuration overrides. Here's what I use:

`$ watch -n 1 --no-title --color task rc._forcecolor:on rc.defaultwidth:120 rc.detection:off`
