### ISSUE TITLE
[TS-29] tasksh hangs trying to read task from stdin

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskshell#28]
_ilovezfs on 2016-09-06T08:34:22Z says:_ 

 I opened an initial pull request for tasksh 1.1.0 to homebrew/core. CI fails during the testing phase because the test hangs. We run the following test:
```
  test do
    system "#{bin}/tasksh", "--version"
    (testpath/".taskrc").write "data.location=#{testpath}/.task\n"
    assert_match(/Created task 1./, pipe_output("#{bin}/tasksh", "add Test Task"))
  end
```
The first command `tasksh --version` is fine. However, the second command hangs. The pipe_output function is the equivalent of
```
echo -n "add Test Task" | tasksh
```
I bisected the problem, which doesn't affect 1.0.0, and determined that this is a regression caused by https://git.tasktools.org/projects/EX/repos/tasksh/commits/b783adca92f9cb6881bb1e3da6663b3391e35b8c

The following patch seems to have fixed the problem:
```
diff --git a/src/main.cpp b/src/main.cpp
index 556e7b3..e5384ee 100644
* -- a/src/main.cpp
+++ b/src/main.cpp
@@ -31,6 +31,7 @@
1. include <cstring>
1. include <stdlib.h>
1. include <shared.h>
+#include <unistd.h>
1. ifdef HAVE_READLINE
1. include <readline/readline.h>
@@ -124,7 +125,8 @@ static int commandLoop (bool autoClear)
       // Deliberately ignoreѕ taskwarrior exit status, otherwise empty filters
       // cause the shell to terminate.
     }
*   }
+  } else
+    return -1;
 
   return status;
 }
@@ -155,7 +157,9 @@ int main (int argc, const char** argv)
                    output == "yes\n"  ||
                    output == "on\n");
*       welcome ();
+      if (isatty(fileno(stdin)))
+        welcome ();
+
       while ((status = commandLoop (autoClear)) == 0)
         ;
     }
```
I have also attached the patch file.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2016-09-06T08:34:22Z
Modified: 2016-09-06T12:13:40Z
```

**Comment by pbeckingham** [comment]
[TS-29_tasksh-1.1.0-fix-hang.patch.txt](https://github.com/GothenburgBitFactory/taskshell/files/1755289/TS-29_tasksh-1.1.0-fix-hang.patch.txt)
