### ISSUE TITLE
[TS-30] Let review use a filter

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskshell#29]
_Dirk Deimeke on 2016-09-07T07:57:19Z says:_ 

 It would be great to have review use a filter.

Review is a great command, which operates on "status:waiting" tasks as well. It would be great, if one could limit the review processing to only "status:pending" tasks.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2016-09-07T07:57:19Z
Modified: 2017-01-17T02:06:01Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2016-09-07T11:42:46Z says:_ 

 You can: On first use, the review feature sets up a UDA ("reviewed", type date), and a custom report ("_reviewed"), which has a modifiable filter.

Or did you mean that the default should change?

**Comment by taskwarrior** [comment]
_Dirk Deimeke on 2016-09-07T15:45:46Z says:_ 

 No, I thought about an extra option for the review command.

```
tasksh> review [filter] [N]
```

Filter can be any filter.

Sometimes it is important to review only tasks by project or by something else and I don't think it is a good idea to change the taskrc-file everytime.

```
tasksh> review project:work
tasksh> review project:work status:pending
tasksh> review project:home status:waiting
```

**Comment by taskwarrior** [comment]
_David Patrick on 2016-09-10T04:19:18Z says:_ 

 +1

**Comment by MartyLake** [comment]
+1
