### ISSUE TITLE
[TS-32] control-d to exit

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskshell#31]
_Eric Hymowitz on 2016-11-11T14:01:57Z says:_ 

 Most interactive programs allow EOF (control-d) to serve as an "exit" command.  tasksh does not.  It seems to trap EOF and just continue with a new prompt.

Please consider adding this feature to tasksh, unless it was specifically declined for some reason I don't know.

(I genuinely don't know if this is an "issue" or a "bug" or just a "question", and I don't want to upset you again.  Please know that my genuine goal is to make taskwarrior better and/or more usable.)

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2016-11-11T14:01:57Z
Modified: 2017-02-21T04:19:11Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2016-11-11T22:21:39Z says:_ 

 Good suggestion, thanks.  This is the correct place for this, and you chose "Improvement" as the issue type, which is correct, although it could easily have been a "New feature".  The distinction is unimportant in this case.

No one is upset, by the way.  Hope you're not.  Hope you don't mind terse answers from busy people.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2016-11-11T22:43:47Z says:_ 

 Fixed.

**Comment by taskwarrior** [comment]
_Paul Fenwick on 2017-02-21T02:14:46Z says:_ 

 I've just built d5bd17c on Ubuntu 14.04, and hitting Ctrl-D seems to cause an endless loop, rather than exiting tasksh. I can enter '<EOF>', which *does* cause tasksh to exit, so I'm pretty sure I've built the commit that implements this.

On closer inspection it appears that Ctrl-D checking open happens if tasksh is built with readline support.

I'm still learning the taskwarrior change processes, but I have a patch that fixes this. :)

**Comment by taskwarrior** [comment]
_Paul Fenwick on 2017-02-21T02:16:30Z says:_ 

 Added file: Patch that corrects this on non-readline systems. Generated with `git format-patch`

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2017-02-21T04:19:11Z says:_ 

 Good patch, thanks.  Applied and pushed.  AUTHORS file updated.

**Comment by pbeckingham** [comment]
[TS-32_0001-TS-32-Exit-on-Ctrl-D-on-non-readline-systems.patch.txt](https://github.com/GothenburgBitFactory/taskshell/files/1755288/TS-32_0001-TS-32-Exit-on-Ctrl-D-on-non-readline-systems.patch.txt)
