### ISSUE TITLE
[TS-37] Can't clone tasksh

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskshell#36]
_MartyLake on 2017-05-03T18:19:14Z says:_ 

 I tried to follow the clone instructions here https://tasktools.org/projects/tasksh.html

And I get the attached Result.

Best,
* ----------------------
matthieu(at)matthieu-Inspiron-7559:~/Desktop$ git clone --recursive https://git.tasktools.org/EX/tasksh.git
Cloning into 'tasksh'...
remote: Counting objects: 1041, done.
remote: Compressing objects: 100% (330/330), done.
remote: Total 1041 (delta 692), reused 1024 (delta 686)
Receiving objects: 100% (1041/1041), 172.60 KiB | 173.00 KiB/s, done.
Resolving deltas: 100% (692/692), done.
Checking connectivity... done.
Submodule 'src/libshared' (https://git.tasktools.org/scm/tm/libshared.git) registered for path 'src/libshared'
Cloning into 'src/libshared'...
fatal: repository 'https://git.tasktools.org/scm/tm/libshared.git/' not found
fatal: clone of 'https://git.tasktools.org/scm/tm/libshared.git' into submodule path 'src/libshared' failed
matthieu(at)matthieu-Inspiron-7559:~/Desktop$ cd tasksh/
matthieu(at)matthieu-Inspiron-7559:~/Desktop/tasksh$ git submodule init
matthieu(at)matthieu-Inspiron-7559:~/Desktop/tasksh$ git submodule update
Cloning into 'src/libshared'...
fatal: repository 'https://git.tasktools.org/scm/tm/libshared.git/' not found
fatal: clone of 'https://git.tasktools.org/scm/tm/libshared.git' into submodule path 'src/libshared' failed

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2017-05-03T18:19:14Z
Modified: 2017-05-09T17:12:11Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2017-05-04T04:30:01Z says:_ 

 Hi Marty,

This is because we moved our repositories to a new server, and the URLs are different.  We fixed this, but only in the development branches, and when we release the current development branch, it will get merged to master, and this will be solved.  You have two options:

1) Clone the dev branch:

    `git clone --recursive -b 1.2.0 https://git.tasktools.org/EX/tasksh.git`

2) Download the source tarball for the stable release:

    `curl -O https://taskwarrior.org/download/tasksh-1.1.0.tar.gz`

**Comment by taskwarrior** [comment]
_MartyLake on 2017-05-09T16:53:01Z says:_ 

 Hi Paul ! I did clone the dev branch 1.2.0, and succesfully built tasksh with readline support.

Thanks for the complete support, and hope the dev branch gets merged soon so the website gets accurate again :)

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2017-05-09T17:12:11Z says:_ 

 You're right, 1.2.0 has several good fixes in it.  Let's release it.

**Comment by MartyLake** [comment]
Hello,

I have the same problem again:

    git clone --recursive -b 1.3.0 https://git.tasktools.org/EX/tasksh.git

is timing out, and

    git clone --recursive -b 1.3.0 https://github.com/GothenburgBitFactory/taskshell

clones ok, and generates ok, but the projects fails to build saying "invalid numeric argument /Wextra"
