### ISSUE TITLE
git.tasktoools.org is down

### ISSUE THREAD

**Issue by blaisegarant** [GothenburgBitFactory/taskshell#63]
The git.tasktools.org website is down and therefore, libshared can't be downloaded.

Anyone still has that source code?

**Comment by pbeckingham** [comment]
All source code (projects and websites) moved to GitHub some time ago.

https://github.com/GothenburgBitFactory

**Comment by blaisegarant** [comment]
But the link wasn't updated
https://github.com/GothenburgBitFactory/taskshell/pull/62
